name: Tests
on:
  pull_request:
    branches:
      - main
permissions:
  contents: read

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
        python_version: [ "3.10", "3.11", "3.12", "3.13" ]
    concurrency:
      group: tests-${{ github.event_name == 'push' && github.run_number || github.ref }}-${{ matrix.os }}-${{ matrix.python_version }}
      cancel-in-progress: true
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}

      - name: Upgrade pip
        run: pip install --upgrade pip wheel uv

      - name: Install package dependencies
        run: uv pip install .[test]

      - name: Show versions
        run: uv pip freeze

      - name: Run tests
        run: pytest tests/
